/* eslint-disable */
// This file is generated by chrome-i18n-code-gen, do not edit it

export type ChromeI18nKeys = "extName" | "extDescription" | "rulesTabName" | "settingsTabName" | "settingSectionProxy" | "settingSectionGeneral" | "settingSectionWhistle" | "proxyStatusOn" | "proxyStatusOff" | "proxyStatusTitleOn" | "proxyStatusTitleOff" | "settingAutoRefresh" | "settingThemeFollowSystem" | "settingIpv4" | "settingDarkMode" | "settingUseMultiple" | "openWhistleTitle" | "whistleHost" | "WhistlePort" | "WhistleGuiPort" | "FreePort" | "titleClipboard"

export default function i18n(key: ChromeI18nKeys): string {
    return chrome.i18n.getMessage(key)
}
        

export function extName(): string {
    return chrome.i18n.getMessage('extName')
}
            

export function extDescription(): string {
    return chrome.i18n.getMessage('extDescription')
}
            

export function rulesTabName(): string {
    return chrome.i18n.getMessage('rulesTabName')
}
            

export function settingsTabName(): string {
    return chrome.i18n.getMessage('settingsTabName')
}
            

export function settingSectionProxy(): string {
    return chrome.i18n.getMessage('settingSectionProxy')
}
            

export function settingSectionGeneral(): string {
    return chrome.i18n.getMessage('settingSectionGeneral')
}
            

export function settingSectionWhistle(): string {
    return chrome.i18n.getMessage('settingSectionWhistle')
}
            

export function proxyStatusOn(): string {
    return chrome.i18n.getMessage('proxyStatusOn')
}
            

export function proxyStatusOff(): string {
    return chrome.i18n.getMessage('proxyStatusOff')
}
            

export function proxyStatusTitleOn(): string {
    return chrome.i18n.getMessage('proxyStatusTitleOn')
}
            

export function proxyStatusTitleOff(): string {
    return chrome.i18n.getMessage('proxyStatusTitleOff')
}
            

export function settingAutoRefresh(): string {
    return chrome.i18n.getMessage('settingAutoRefresh')
}
            

export function settingThemeFollowSystem(): string {
    return chrome.i18n.getMessage('settingThemeFollowSystem')
}
            

export function settingIpv4(): string {
    return chrome.i18n.getMessage('settingIpv4')
}
            

export function settingDarkMode(): string {
    return chrome.i18n.getMessage('settingDarkMode')
}
            

export function settingUseMultiple(): string {
    return chrome.i18n.getMessage('settingUseMultiple')
}
            

export function openWhistleTitle(): string {
    return chrome.i18n.getMessage('openWhistleTitle')
}
            

export function whistleHost(): string {
    return chrome.i18n.getMessage('whistleHost')
}
            

export function WhistlePort(): string {
    return chrome.i18n.getMessage('WhistlePort')
}
            

export function WhistleGuiPort(): string {
    return chrome.i18n.getMessage('WhistleGuiPort')
}
            

export function FreePort(): string {
    return chrome.i18n.getMessage('FreePort')
}
            

export function titleClipboard(): string {
    return chrome.i18n.getMessage('titleClipboard')
}
            